Update draft-terbu-sd-jwt-vc.md
vcstuff/draft-terbu-sd-jwt-vc pull request #132
Opened 2023-06-16 19:26 UTC by OR13

2023-06-16 19:27 UTC, mprorock commented on draft-terbu-sd-jwt-vc.md
>  abbrev = "SD-JWT VC"
```suggestion
abbrev = "JWT-VC"
```

2023-06-16 19:28 UTC, OR13 commented on draft-terbu-sd-jwt-vc.md
>  abbrev = "SD-JWT VC"
^ can we reverse to "VC-JWT" ?

2023-06-16 19:28 UTC, mprorock approved these changes
approve of this but see suggestion on abbrev

2023-06-16 19:28 UTC, mprorock commented on draft-terbu-sd-jwt-vc.md
>  abbrev = "SD-JWT VC"
totally good with that

2023-06-17 04:10 UTC, OR13 reviewed
Reasoning for name change.

1. Verifiable Credential is the new part not JWT or SD-JWT.
2. This item focuses on securing Verifiable Credential with 2 existing IETF work items, so you can't start the name of the work item with 2 formats, but you can start it with the name of the thing that has 2 secured representations.
3. This is truly the vc-jwt spec, the one at W3C is focused on vc+ld+json... We should make the names as simple and clear as possible.
4. Putting JWT first is not correct, if the typ values differ in the spec and don't both use +jwt suffix (this is a variation on 2).

2023-06-19 19:32 UTC, selfissued approved these changes
the "with JSON payloads" wording is clunky and redundant.  All JWTs have JSON payloads.

2023-06-19 19:59 UTC, Sakurann requested changes
we need to make a decision whether to go #120 or #131 path. and I am personally more and more favorable towards #131. and this PR is more inline with #120 than #131.

2023-06-19 20:01 UTC, Sakurann commented
> the "with JSON payloads" wording is clunky and redundant. All JWTs have JSON payloads.

but not all JWS, which can sign anything. this is a way to draw a line with a document in W3C which uses JWS to sign over JSON-LD.

2023-06-26 13:54 UTC, OR13 commented
Closing this PR, we will try again later.... this document should be titled vc-jwt, since it does not describe securing other content types.

2023-06-26 13:54 UTC, closed without merging