improve reasoning for SD-JWT
vcstuff/draft-terbu-sd-jwt-vc pull request #95
Opened 2023-05-25 15:55 UTC by paulbastian

See #94

2023-05-25 16:00 UTC, tlodderstedt approved these changes

2023-05-25 16:17 UTC, peppelinux requested changes

2023-05-25 16:17 UTC, peppelinux commented on draft-terbu-sd-jwt-vc.md
> +disclosure, i.e., the ability for a holder to disclose only a subset of the contained
holder -> Holder

defined term

2023-05-26 09:07 UTC, awoie approved these changes
lgtm

2023-05-26 09:08 UTC, awoie commented
Merging, two approvals.

2023-05-26 09:08 UTC, merged

2023-05-26 09:09 UTC, awoie commented
fixed #94